### ISSUE TITLE
App crash on cancel

### ISSUE THREAD

**Issue by HeyKos** [apcurium/xamarin-bindings#4]
I included the project in my solution, and can successfully launch the TOCropViewController & get image data back. The issue I run into is when tapping the "Cancel" button on the TOCropViewController. It throws a runtime error, "System.Threading.Tasks.TaskCanceledException: A task was canceled.". Is there a way to dismiss the view controller when cancel is tapped?

Here is how I am invoking the view controller.

```
private async void OnPhotoPicked(NSDictionary obj)
{
    var photo = obj.ValueForKey(new NSString("UIImagePickerControllerOriginalImage")) as UIImage;
    var viewController = new TOCropViewController(photo);
    var rootViewController = UIApplication.SharedApplication.Delegate.GetWindow().RootViewController;
    viewController.DefaultAspectRatio = TOCropViewControllerAspectRatio.Square;
    var imageBytes = await viewController.ShowCropViewAsync(rootViewController, true, null);
}
```

**Comment by dominiquesavoie** [comment]
You need to handle the TaskCancelException case. We actually cancel the task completion source when the user press cancel and then we dismiss the crop view in our internal delegate. This is done to notify the awaiting method that the user cancelled without having to return some kind of CropOperationObject. Here's an example:

```
try
{
var viewController = new TOCropViewController(photo);
    var rootViewController = UIApplication.SharedApplication.Delegate.GetWindow().RootViewController;
    viewController.DefaultAspectRatio = TOCropViewControllerAspectRatio.Square;
    var imageBytes = await viewController.ShowCropViewAsync(rootViewController, true, null);
}
catch(TaskCancelException)
{
   //Log something in the console and/or display the photo picker again.
}
```

**Comment by HeyKos** [comment]
Thanks! That is just what I needed!
